### ISSUE TITLE
serverPort is not compatible to Azure App Service pipes

### ISSUE THREAD

**Issue by DarthSonic** [AntonioMA/swagger-boilerplate#9]
Hi,

have a problem running a node.js app (OpenTok RTC V2) on Azure App Service.

```
const serverPort = process.env.PORT || 8123;
const SwaggerServer = require('swagger-boilerplate').Server;
const server = new SwaggerServer({
  apiFile: './api.yml',
  modulePath: `${__dirname}/server/`,
  appName: 'OpenTokRTC Main',
  serverPort: serverPort,
  staticOptions: {
    dotfiles: 'ignore',
    extensions: ['jpg'],
    index: false,
    redirect: false,
  },
});

server.start();
```

Problem is that serverPort is something like "\\.\pipe\25387797-4dbd-4475-91d2-cf8873ac3aad" in Azure App Service, cause there is no integer port used but a pipe that the entry port gets forwarded to.

So I will get error: "ENOENT: no such file or directory, open 'C:\home\site\wwwroot\otrtc_\pipe\e8dbf4f3-3786-4c4a-8cc3-a460c2926edb.pid'" because the filename for the .pid file is malformed as a path that does not exist.

Unfortunatly azure app service is not accepting requests if I change port to some other. Can not get node.js to run on custom port.

Is there allready a solution for that problem? 

Thanks in advance,
Sven

**Comment by DarthSonic** [comment]
If I set a fixed port 8123 the error is:

```
Error: listen EADDRINUSE: address already in use :::8123
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at C:\home\site\wwwroot\node_modules\swagger-boilerplate\lib\server.js:103:9
```
